version: '3.7'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    env_file:
      - 'compose/env.grafana'
    user: "0"
    volumes:
      - ./compose/data-grafana/:/var/lib/grafana
      - ./compose/conf-grafana/:/etc/grafana/provisioning/
      - ./compose/conf-grafana/grafana.ini:/etc/grafana/grafana.ini

  prometheus:
    image: prom/prometheus:v2.5.0
    volumes:
      - ./compose/data-prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"

  konduit-demo:
     image: konduit/konduit-serving-demo:cpu
     runtime: ${RUNTIME:-runc}
     ports:
       - "8889:8889"
       - "9008:9008"
       - "9009:9009"
     volumes:
       - ./demos:/root/konduit/demos
       - ./konduit.jar:/root/konduit/konduit.jar
     depends_on:
       - prometheus
