{
 "title": "Pipeline Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Running GPUs",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "system_gpu_count" }
   ]
  },
  {
   "title": "Temp GPUs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".*temp_celcius.*\"}"
    }
   ]
  },
  {
   "title": "Memory Usage (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".*percent_memory_usage.*\"}"
    }
   ]
  },
  {
   "title": "Memory Usage (MB)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".*memory_usage_megabytes.*\"}"
    }
   ]
  },
  {
   "title": "GPU Utilization (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".*percent_gpu_usage.*\"}"
    }
   ]
  },
  {
   "title": "Fan Speeds (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".*fan_speed.*\"}"
    },
    {
     "expr": "m_1_geforce_rtx_2080_ti__fan_speed_rpm"
    }
   ]
  },
  {
   "title": "Server up time (seconds)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "server_up_time_total", "legendFormat": "Rate of Inference" }
   ]
  },
  {
   "title": "Classification Labels Seen",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 3, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Number_0_classification_outcome_total",
     "legendFormat": "0"
    },
    {
     "expr": "Number_1_classification_outcome_total",
     "legendFormat": "1"
    },
    {
     "expr": "Number_2_classification_outcome_total",
     "legendFormat": "2"
    },
    {
     "expr": "Number_3_classification_outcome_total",
     "legendFormat": "3"
    },
    {
     "expr": "Number_4_classification_outcome_total",
     "legendFormat": "4"
    },
    {
     "expr": "Number_5_classification_outcome_total",
     "legendFormat": "5"
    },
    {
     "expr": "Number_6_classification_outcome_total",
     "legendFormat": "6"
    },
    {
     "expr": "Number_7_classification_outcome_total",
     "legendFormat": "7"
    },
    {
     "expr": "Number_8_classification_outcome_total",
     "legendFormat": "8"
    },
    {
     "expr": "Number_9_classification_outcome_total",
     "legendFormat": "9"
    }
   ]
  },
  {
   "title": "Classification Labels Seen (Series)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "Number_0_classification_outcome_total",
     "legendFormat": "0"
    },
    {
     "expr": "Number_1_classification_outcome_total",
     "legendFormat": "1"
    },
    {
     "expr": "Number_2_classification_outcome_total",
     "legendFormat": "2"
    },
    {
     "expr": "Number_3_classification_outcome_total",
     "legendFormat": "3"
    },
    {
     "expr": "Number_4_classification_outcome_total",
     "legendFormat": "4"
    },
    {
     "expr": "Number_5_classification_outcome_total",
     "legendFormat": "5"
    },
    {
     "expr": "Number_6_classification_outcome_total",
     "legendFormat": "6"
    },
    {
     "expr": "Number_7_classification_outcome_total",
     "legendFormat": "7"
    },
    {
     "expr": "Number_8_classification_outcome_total",
     "legendFormat": "8"
    },
    {
     "expr": "Number_9_classification_outcome_total",
     "legendFormat": "9"
    }
   ]
  },
  {
   "title": "Requests Handled",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "requests_handled_total", "legendFormat": "Requests Handled" }
   ]
  },
  {
   "title": "Throughput",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(requests_handled_total[5m])",
     "legendFormat": "Rate of Inference"
    }
   ]
  },
  {
   "title": "System Cores",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "system_cpu_count" }
   ]
  },
  {
   "title": "Classification Labels Seen (Log base 2)",
   "type": "graph",
   "gridPos": { "h": 15, "w": 7, "x": 3, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Number_0_classification_outcome_total",
     "legendFormat": "0"
    },
    {
     "expr": "Number_1_classification_outcome_total",
     "legendFormat": "1"
    },
    {
     "expr": "Number_2_classification_outcome_total",
     "legendFormat": "2"
    },
    {
     "expr": "Number_3_classification_outcome_total",
     "legendFormat": "3"
    },
    {
     "expr": "Number_4_classification_outcome_total",
     "legendFormat": "4"
    },
    {
     "expr": "Number_5_classification_outcome_total",
     "legendFormat": "5"
    },
    {
     "expr": "Number_6_classification_outcome_total",
     "legendFormat": "6"
    },
    {
     "expr": "Number_7_classification_outcome_total",
     "legendFormat": "7"
    },
    {
     "expr": "Number_8_classification_outcome_total",
     "legendFormat": "8"
    },
    {
     "expr": "Number_9_classification_outcome_total",
     "legendFormat": "9"
    }
   ]
  },
  {
   "title": "Classification Labels Seen (Series)",
   "type": "graph",
   "gridPos": { "h": 15, "w": 14, "x": 10, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Number_0_classification_outcome_total",
     "legendFormat": "0"
    },
    {
     "expr": "Number_1_classification_outcome_total",
     "legendFormat": "1"
    },
    {
     "expr": "Number_2_classification_outcome_total",
     "legendFormat": "2"
    },
    {
     "expr": "Number_3_classification_outcome_total",
     "legendFormat": "3"
    },
    {
     "expr": "Number_4_classification_outcome_total",
     "legendFormat": "4"
    },
    {
     "expr": "Number_5_classification_outcome_total",
     "legendFormat": "5"
    },
    {
     "expr": "Number_6_classification_outcome_total",
     "legendFormat": "6"
    },
    {
     "expr": "Number_7_classification_outcome_total",
     "legendFormat": "7"
    },
    {
     "expr": "Number_8_classification_outcome_total",
     "legendFormat": "8"
    },
    {
     "expr": "Number_9_classification_outcome_total",
     "legendFormat": "9"
    }
   ]
  },
  {
   "title": "Total CPU Usage (%)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "system_cpu_usage * 100", "legendFormat": "Total CPU Usage" }
   ]
  },
  {
   "title": "Memory Usage (MB)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes / 1024 / 1024",
     "legendFormat": "{{id}}"
    }
   ]
  }
 ]
}